Add (commented) logic to webupdate{,.wrapper} to prepare for the conversion of the doc tree from Subversion to Git.
Sponsored by:	Rubicon Communications, LLC (netgate.com)

diff --git a/share/tools/webupdate b/share/tools/webupdate
--- a/share/tools/webupdate
+++ b/share/tools/webupdate
@@ -15,6 +15,7 @@
 #
 #	PATH		- The search path as interpreted by the shell.
 #	SVNROOT		- Path to the FreeBSD SVN repository.
+#	GITROOT		- Path to the FreeBSD Git repository.
 #	BUILDDIR	- Where the checked out copies of the files are stored.
 #	DESTDIR		- Where the rendered copies should wind up.
 #	PUBDIR		- Where the rendered files are published.
@@ -35,7 +36,7 @@
 #
 #	0	- success
 #	1	- unknown failure
-#	2	- failure in SVN operations
+#	2	- failure in VCS operations
 #	3	- failure in make operations
 #
 # $FreeBSD$
@@ -46,6 +47,7 @@
 #
 DEFAULT_PATH=/bin:/usr/bin:/usr/local/bin;
 DEFAULT_SVNROOT=svn://svn.FreeBSD.org
+#DEFAULT_GITROOT=https://cgit-beta.FreeBSD.org
 DEFAULT_BUILDDIR=/usr/local/www/build;
 #DEFAULT_LOGDIR=/usr/local/www/build/log;
 DEFAULT_LOGDIR=/usr/local/www/logs/build;
@@ -62,6 +64,7 @@ DEFAULT_WEBMAILTO=freebsd-doc;
 #
 PATH=${PATH:-${DEFAULT_PATH}}; export PATH;
 SVNROOT=${SVNROOT:-${DEFAULT_SVNROOT}}; export SVNROOT;
+#GITROOT=${GITROOT:-${DEFAULT_GITROOT}}; export GITROOT;
 BUILDDIR=${BUILDDIR:-${DEFAULT_BUILDDIR}};
 LOGDIR=${LOGDIR:-${DEFAULT_LOGDIR}};
 DESTDIR=${DESTDIR:-${DEFAULT_DESTDIR}}; export DESTDIR
@@ -91,6 +94,7 @@ export NO_OBJ=YES
 subtrees='head src/share/man/man4
 relnotes11/doc relnotes11/man4
 ports';
+#subtrees="${subtrees} main"
 
 #
 # Update the checked out copies.  Check out new copies every Sunday or
@@ -126,6 +130,7 @@ if [ $cond ]; then
 
 	# Check out the new copies.  This creates all the $subtrees.
 	svn co $SVNROOT/doc/head head >> $LOGFILE 2>&1 || exit 2;
+	#git clone -b main $GITROOT/doc.git main >> $LOGFILE 2>&1 || exit 2;
 
 	test -d relnotes || mkdir relnotes;
 	mkdir -p src/share/man/man4
@@ -139,6 +144,8 @@ else
 	for dir in ${subtrees}; do
 		svn cleanup $dir >> $LOGFILE 2>&1 || exit 2;
 		svn update --accept theirs-full $dir >> $LOGFILE 2>&1 || exit 2;
+		#git -C main clean -f >> $LOGFILE 2>&1 || exit 2;
+		#git -C main pull >> $LOGFILE 2>&1 || exit 2;
 	done
 fi
 
@@ -151,6 +158,7 @@ fi
 # Build the web site.
 #
 cd $BUILDDIR/head || exit 1;
+#cd $BUILDDIR/main || exit 1;
 
 # get latest revision
 LATESTREVISION=$LOGDIR/LATESTREVISION
@@ -166,6 +174,7 @@ time make ${BUILDARGS} p-all >> $LOGFILE 2>&1 ||
 	 exit 3) || exit 3;
 
 cd $BUILDDIR/head/en_US.ISO8859-1/htdocs || exit 1;
+#cd $BUILDDIR/main/en_US.ISO8859-1/htdocs || exit 1;
 
 ( time make ${INSTARGS} -j8 all && time make ${INSTARGS} install ) >> $LOGFILE 2>&1 ||
 	(cat $LATESTREVISION >> $LOGFILE
