Update the webupdate script to uncomment git calls prior to the switchover for the repository.
Sponsored by:	Rubicon Communications, LLC (netgate.com)


git-svn-id: svn+ssh://svn.freebsd.org/doc/head@54730 c2e8774f-c49f-e111-b436-862b2bbc8956

diff --git a/share/tools/webupdate b/share/tools/webupdate
--- a/share/tools/webupdate
+++ b/share/tools/webupdate
@@ -47,7 +47,7 @@
 #
 DEFAULT_PATH=/bin:/usr/bin:/usr/local/bin;
 DEFAULT_SVNROOT=svn://svn.FreeBSD.org
-#DEFAULT_GITROOT=https://cgit-beta.FreeBSD.org
+DEFAULT_GITROOT=https://cgit-beta.FreeBSD.org
 DEFAULT_BUILDDIR=/usr/local/www/build;
 #DEFAULT_LOGDIR=/usr/local/www/build/log;
 DEFAULT_LOGDIR=/usr/local/www/logs/build;
@@ -64,7 +64,7 @@ DEFAULT_WEBMAILTO=freebsd-doc;
 #
 PATH=${PATH:-${DEFAULT_PATH}}; export PATH;
 SVNROOT=${SVNROOT:-${DEFAULT_SVNROOT}}; export SVNROOT;
-#GITROOT=${GITROOT:-${DEFAULT_GITROOT}}; export GITROOT;
+GITROOT=${GITROOT:-${DEFAULT_GITROOT}}; export GITROOT;
 BUILDDIR=${BUILDDIR:-${DEFAULT_BUILDDIR}};
 LOGDIR=${LOGDIR:-${DEFAULT_LOGDIR}};
 DESTDIR=${DESTDIR:-${DEFAULT_DESTDIR}}; export DESTDIR
@@ -129,8 +129,8 @@ if [ $cond ]; then
 	rm -Rf $subtrees 2>/dev/null;
 
 	# Check out the new copies.  This creates all the $subtrees.
-	svn co $SVNROOT/doc/head head >> $LOGFILE 2>&1 || exit 2;
-	#git clone -b main $GITROOT/doc.git main >> $LOGFILE 2>&1 || exit 2;
+	#svn co $SVNROOT/doc/head head >> $LOGFILE 2>&1 || exit 2;
+	git clone -b main $GITROOT/doc.git main >> $LOGFILE 2>&1 || exit 2;
 
 	test -d relnotes || mkdir relnotes;
 	mkdir -p src/share/man/man4
@@ -142,10 +142,10 @@ if [ $cond ]; then
 	rm -f $BUILDDIR/fullbuild-clean.flag
 else
 	for dir in ${subtrees}; do
-		svn cleanup $dir >> $LOGFILE 2>&1 || exit 2;
-		svn update --accept theirs-full $dir >> $LOGFILE 2>&1 || exit 2;
-		#git -C main clean -f >> $LOGFILE 2>&1 || exit 2;
-		#git -C main pull >> $LOGFILE 2>&1 || exit 2;
+		#svn cleanup $dir >> $LOGFILE 2>&1 || exit 2;
+		#svn update --accept theirs-full $dir >> $LOGFILE 2>&1 || exit 2;
+		git -C main clean -f >> $LOGFILE 2>&1 || exit 2;
+		git -C main pull >> $LOGFILE 2>&1 || exit 2;
 	done
 fi
 
@@ -157,8 +157,8 @@ fi
 #
 # Build the web site.
 #
-cd $BUILDDIR/head || exit 1;
-#cd $BUILDDIR/main || exit 1;
+#cd $BUILDDIR/head || exit 1;
+cd $BUILDDIR/main || exit 1;
 
 # get latest revision
 LATESTREVISION=$LOGDIR/LATESTREVISION
@@ -173,8 +173,8 @@ time make ${BUILDARGS} p-all >> $LOGFILE 2>&1 ||
 			| /usr/sbin/sendmail -oi -f www-data@freebsd.org ${WEBMAILTO};
 	 exit 3) || exit 3;
 
-cd $BUILDDIR/head/en_US.ISO8859-1/htdocs || exit 1;
-#cd $BUILDDIR/main/en_US.ISO8859-1/htdocs || exit 1;
+#cd $BUILDDIR/head/en_US.ISO8859-1/htdocs || exit 1;
+cd $BUILDDIR/main/en_US.ISO8859-1/htdocs || exit 1;
 
 ( time make ${INSTARGS} -j8 all && time make ${INSTARGS} install ) >> $LOGFILE 2>&1 ||
 	(cat $LATESTREVISION >> $LOGFILE
